const fs = require('fs')
const path = require('path')

const packagePath = path.join(__dirname, '..', 'package.json')
const outputPath = path.join(__dirname, '..', 'src', 'lib', 'version.ts')

const pkg = JSON.parse(fs.readFileSync(packagePath, 'utf8'))
const version = pkg.version || '0.0.0'
const generatedAt = new Date().toISOString()

const content = `// This file is auto-generated by scripts/write-version.cjs. Do not edit manually.
export const APP_VERSION = '${version}'
export const APP_VERSION_GENERATED_AT = '${generatedAt}'
`

fs.writeFileSync(outputPath, content)
console.log(`Wrote app version ${version} to src/lib/version.ts`)
